% Code for analysing the immediate change in speed following loom stimuli
% of different contrasts.

% Generated by Burnett. 

rowsb4 = 175;

for i = 1:numel(xy_analysis(:,1)) %numel(all_xy_analysis(:,1))
    
    x = cell2mat(ALL_XYLOOM_TABLE{i,5});  
 
    sp_at = nanmean(x(rowsb4-5:rowsb4+5));
    sp_immed = nanmean(x(rowsb4+15:rowsb4+45)); %nanmean
    
    xy_analysis.speedat{i} = sp_at;
    xy_analysis.speed_immed{i} = sp_immed;

end 


%% Add column to xy_analysis about whether speedIM is </>/= 1SD from speedAT

allWT = find(string(xy_analysis.Geno)=="wt" ); 
avWTspeed = nanmean(cell2mat(xy_analysis.speedat(allWT)));
stdWT = nanstd(cell2mat(xy_analysis.speedat(allWT)));

minWT = avWTspeed-(stdWT/2);
maxWT = avWTspeed+(stdWT/2);

allHET = find(string(xy_analysis.Geno)=="het"); 
avHETspeed = nanmean(cell2mat(xy_analysis.speedat(allHET)));
stdHET = nanstd(cell2mat(xy_analysis.speedat(allHET)));

minHET = avHETspeed-(stdHET/2);
maxHET = avHETspeed+(stdHET/2);

for i = 1:height(xy_analysis)
    
    geno = string(xy_analysis.Geno{i});
    spim = xy_analysis.speed_immed{i};
    
    if geno == "wt"
        
        if spim < minWT
            xy_analysis.GRP{i} = 1;
        elseif spim >= minWT && spim <= maxWT
            xy_analysis.GRP{i} = 2;
        elseif spim > maxWT
            xy_analysis.GRP{i} = 3;
        end 
        
    elseif geno == "het"
        
        if spim < minHET
            xy_analysis.GRP{i} = 1;
        elseif spim >= minHET && spim <= maxHET
            xy_analysis.GRP{i} = 2;
        elseif spim > maxHET
            xy_analysis.GRP{i} = 3;
        end 
    end 
    
end 



%% STACKED BAR CHART for each contrast value

VALSW = []; 
VALSH = []; 

for i = [4,3,1]
    
    for j = 1:2
        
        if j == 1

            rows = find(string(xy_analysis.Geno)=="wt" & cell2mat(xy_analysis.Contrast)==i & cell2mat(xy_analysis.speedat)>1 & cell2mat(xy_analysis.ReturnToShelter)==1);
            
            n = numel(rows);
            all1 = find(cell2mat(xy_analysis.GRP(rows))==1);
            all2 = find(cell2mat(xy_analysis.GRP(rows))==2);
            all3 = find(cell2mat(xy_analysis.GRP(rows))==3);
            
            vals = [numel(all1)/n, numel(all2)/n, numel(all3)/n];
            
            VALSW = vertcat(VALSW, vals);
            
        elseif j == 2

            rows = find(string(xy_analysis.Geno)=="het" & cell2mat(xy_analysis.Contrast)==i & cell2mat(xy_analysis.speedat)>1 & cell2mat(xy_analysis.ReturnToShelter)==1);

            n = numel(rows);
            all1 = find(cell2mat(xy_analysis.GRP(rows))==1);
            all2 = find(cell2mat(xy_analysis.GRP(rows))==2);
            all3 = find(cell2mat(xy_analysis.GRP(rows))==3);
            
            vals = [numel(all1)/n, numel(all2)/n, numel(all3)/n];
            
            VALSH = vertcat(VALSH, vals);
            
        end
    end 
 
end 

        figure
        subplot(2,1,1) 
        b1 = bar(VALSW,'stacked');
        b1(1).LineWidth = 1.2;
        b1(2).LineWidth = 1.2;
        b1(3).LineWidth = 1.2;
        b1(1).FaceColor = [0.2 0.2 0.2]; %[0.39 0 0.6];
        b1(2).FaceColor = [0.8 0.8 0.8];
        b1(3).FaceColor = [1 1 1]; %[0.3 0.7 0.9];
        ax = gca;
        ax.LineWidth = 1.25;
        ax.TickDir = 'out';
        ax.TickLength = [0.02 0.02];
       
        box off
        subplot(2,1,2)
        b2 = bar(VALSH,'stacked');  
        b2(1).FaceColor = [0.2 0.2 0.2 ]; %[0.39 0 0.6];
        b2(2).FaceColor = [0.8 0.8 0.8];
        b2(3).FaceColor = [1 1 1]; %[0.3 0.7 0.9];
        b2(1).LineWidth = 1.2;
        b2(2).LineWidth = 1.2;
        b2(3).LineWidth = 1.2;
        box off
        ax = gca;
        ax.LineWidth = 1.25;
        ax.TickDir = 'out';
        ax.TickLength = [0.02 0.02];
        
        f = gcf;
        f.Position = [440   104   420   694]; 
   

        
        %%
        
        allWT = find(string(xy_analysis.Geno) == "wt" & cell2mat(xy_analysis.Contrast) == 4);
        allHET = find(string(xy_analysis.Geno) == "het"  & cell2mat(xy_analysis.Contrast) == 4);
        
        wtvals = cell2mat(xy_analysis.GRP(allWT));
        hetvals = cell2mat(xy_analysis.GRP(allHET));
        
        w1 = repmat("WT", numel(wtvals),1);
        h1 = repmat("HET", numel(hetvals),1);
        
        x1 = [w1', h1']';
        x2 = [wtvals; hetvals];
        [tbl, chi2stat, pval] = crosstab(x1, x2)
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        %%
% %%  Stats - distribution / proportion - all LPs
% 
% allWT = find(string(xy_return.Geno) == "wt");
% allHET = find(string(xy_return.Geno) == "het");
% 
% wtvals = cell2mat(xy_return.GRP(allWT));
% hetvals = cell2mat(xy_return.GRP(allHET));
% 
% w1 = repmat("WT", numel(wtvals),1);
% h1 = repmat("HET", numel(hetvals),1);
% 
% x1 = [w1', h1']';
% x2 = [wtvals; hetvals];
% [tbl, chi2stat, pval] = crosstab(x1, x2)






